/* eslint-disable react/jsx-no-undef */
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";
import Header from "@/components/Header/Header";
import Footer from "@/components/Footer/Footer";

import { ToastContainer, toast } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';
import SessionProvider from '@/utils/SessionProvider'
import { getServerSession } from "next-auth";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Swift-cart",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const session =  getServerSession();
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        <SessionProvider session={session}>
          <Header></Header>
          {children}
          <Footer></Footer>
        </SessionProvider>
          <ToastContainer />
        <Script src="https://unpkg.com/ionicons@latest/dist/ionicons.js" />
      </body>
    </html>
  );
}
