/* eslint-disable react/jsx-no-undef */
import { Inter } from "next/font/google";
import "./globals.css";
import Script from "next/script";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" data-theme="light">
      <body className={inter.className}>
        {children}
        <Script src="https://unpkg.com/ionicons@latest/dist/ionicons.js" />
      </body>
    </html>
  );
}
